language: node_js
node_js:
  - "6.4"
  - "6.3"
  - "6.2"
  - "6.1"
  - "6.0"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
    - master

services:
  - mongodb
  - redis-server

before_script:
  - mongo mydb_test --eval 'db.addUser("travis", "rozu");'
