language: node_js
node_js:
  - "5.3"
  - "5.2"
  - "5.1"
  - "5.0"
  - "4.2"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
    - master

services:
  - mongodb
  - redis-server

before_script:
  - mongo mydb_test --eval 'db.addUser("travis", "rozu");'