( function () {
	"use strict";

	var ROOT = __dirname + "/../",
		ROOT_ROUTES = [],
		VERSION = "{{VERSION}}",
		SSE = require("express-sse"),
		tenso = require("tenso"),
		keigai = require("keigai"),
		bcrypt = require("bcrypt"),
		redis = require("redis"),
		nodemailer = require("nodemailer"),
		uuid = require("node-uuid").v1,
		mpass = require("mpass"),
		config = require(ROOT + "config.json"),
		jsonpatch = require("jsonpatch").apply_patch,
		request = require("request"),
		store = keigai.store,
		util = keigai.util,
		array = util.array,
		clone = util.clone,
		deferred = util.defer,
		iterate = util.iterate,
		json = util.json,
		lru = util.lru,
		merge = util.merge,
		when = util.when,
		collections = lru(config.collection || 1000),
		sse = new SSE(),
		app, mta, clientPublish, clientSubscribe;
